### ISSUE TITLE
Input redirection error on Windows

### ISSUE THREAD

**Issue by SeanSnyders** [nfischer/shelljs-plugin-sleep#2] opened 2017-05-29 08:00 UTC
On Win 10 x64.

using versions:
```
node 7.4.0
npm 4.5.0
"shelljs": "0.7.7",
shelljs-plugin-sleep": "0.1.0",
```

Trying to do:
 ```
var shell = require('shelljs');
require('shelljs-plugin-sleep');
shell.sleep(5);
```
called via `npm` as a script.
It works fine on macOS 10.12.* but fails on Win 10 x64 with error:

```
ERROR: Input redirection is not supported, exiting the process immediately.
ShellJS: internal error
Error: Command failed: timeout 5
ERROR: Input redirection is not supported, exiting the process immediately.

    at checkExecSyncError (child_process.js:490:13)
    at Object.execSync (child_process.js:530:13)
    at Object.execSleep [as sleep] (<repo>\node_modules\shelljs-plugin-sleep\index.js:8:11)
    at Object.sleepImpl (<repo>\node_modules\shelljs-plugin-sleep\index.js:35:9)
    at Object.sleep <repo>\node_modules\shelljs\src\common.js:383:25)
```

**Comment by nfischer** [comment] 2017-05-30 17:51
@SeanSnyders Thanks for trying this out and reporting the error!

Looks like our CI [might not be covering this case](https://github.com/nfischer/shelljs-plugin-sleep/blob/master/test/test.js#L134).

Any reason why you don't have a C++ compiler installed? That'd be a good workaround until this is fixed.

This should be resolved by #1, I just need to weight the tradeoffs against unix `sleep`. If #1 is suitable, then that test case should be cross-platform, so we can prevent regressions in the future.

**Comment by nfischer** [comment] 2017-05-31 14:08
@SeanSnyders can you try out that branch? Does it help out your issues?

```sh
$ npm install nfischer/shelljs-plugin-sleep#feat-better-fallback
```

**Comment by SeanSnyders** [comment] 2017-05-31 20:56
I can have a look at that branch and see.

> Any reason why you don't have a C++ compiler installed? That'd be a good workaround until this is fixed.

I indeed have a c++ compiler installed on my Win 10 x64 computer: MS VS2105.

In general I have several issues with `sleep` functionality in general between macOS and Windows.
Especially the `async` vs not `async` functionality and when it is called from other packages like Electron. 
To get consistent behaviour in the several cases I have tested, I find that on Windows I need to use the fallback directly (i.e. `childProcess.execSync`) and on macOS it seems to use the `Promise` as expected. Still need to make sure about the sync vs. async on Windows....

**Comment by nfischer** [comment] 2017-06-01 03:56
> I indeed have a c++ compiler installed on my Win 10 x64 computer: MS VS2015.

Seems like npm isn't able to pick up on it. This module depends on the sleep package, which is a C++ native extension. If I recall correctly, compilation happens during `npm install`. So if we're using a fallback approach, that means that npm couldn't find a C++ compiler to build the package.

But I could be mistaken, I'm not well-versed in native extensions.

**Comment by SeanSnyders** [comment] 2017-06-01 05:43
My other native extensions compile fine, e.g. Edge.

The typical system `sleep` command/api is only available on `*nix` platforms (unistd.h), not Windows.
But I see you depend on https://github.com/erikdubbelboer/node-sleep which has some implementation of a 'sleep' function for windows: https://github.com/erikdubbelboer/node-sleep/blob/master/sleep.cc#L11

One needs to test that specifically to see if the correct function does indeed get called in that library.

**Comment by nfischer** [comment] 2017-06-02 07:08
> My other native extensions compile fine, e.g. Edge.

I've only seen us use the fallback functions if [`node-sleep` fails to install](https://github.com/nfischer/shelljs-plugin-sleep/blob/master/index.js#L30). This usually means the native extension didn't compile.

Can you provide output for `ls -R path/to/your/project/node_modules/sleep/` (or the equivalent Win command)?

> The typical system sleep command/api is only available on *nix platforms (unistd.h), not Windows.

I misunderstood you. To me, "command" means shell command (i.e. `man 1 sleep`), I didn't realize you meant the function (i.e. `man 3 sleep`).

> One needs to test that specifically to see if the correct function does indeed get called in that library.

Right now [integration tests](https://ci.appveyor.com/project/shelljs/shelljs-plugin-sleep/branch/master) pass. Ideally, it shouldn't matter if they're using node-sleep or the fallback, as long as things work on appveyor.

> I can have a look at that branch and see.

Any word on if the branch fixes things for you? If so, I'll land the change as the primary fallback.

**Comment by nfischer** [comment] 2017-10-31 06:22
Fix is out, this should resolve issues.

**Closed by nfischer** 2017-10-31 06:22 UTC
Labels: bug
